[email]
address = "sender_account@gmail.com"
smtp_server = "smtp.gmail.com"
imap_server = "imap.gmail.com"
scope = "https://mail.google.com/"

[server]
delta_days = 14
db_path = "friendslist.db"
friends_csv_path = "friends.csv"

[calendar]
url = "https://calendar.google.com/calendar/u/2?cid=some_calendar_id"
scope = "https://www.googleapis.com/auth/calendar.readonly"